### ISSUE TITLE
Bug with FormApi

### ISSUE THREAD

**Issue by dmartin015** [AytgDmr1/AuthUI#3]
20:48:01 Server|CRITICAL > ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/AuthUI.phar/src/aytgdmr1/AuthUI/AuthUI" at line 61
20:48:01 Server|CRITICAL > #0 plugins/AuthUI.phar/src/aytgdmr1/AuthUI/AuthUI(61): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[51] Trying to access array offset on value of type null, string[73] phar:///home/container/plugins/AuthUI.phar/src/aytgdmr1/AuthUI/AuthUI.php, integer 61, array[4])
20:48:01 Server|CRITICAL > #1 plugins/AuthUI.phar/src/aytgdmr1/AuthUI/libs/jojoe77777/FormAPI/Form(46): aytgdmr1\AuthUI\AuthUI->aytgdmr1\AuthUI\{closure}(object pocketmine\Player, NULL )
20:48:01 Server|CRITICAL > #2 src/pocketmine/Player(3865): aytgdmr1\AuthUI\libs\jojoe77777\FormAPI\Form->handleResponse(object pocketmine\Player, NULL )
20:48:01 Server|CRITICAL > #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(307): pocketmine\Player->onFormSubmit(integer 6, NULL )
20:48:01 Server|CRITICAL > #4 src/pocketmine/network/mcpe/protocol/ModalFormResponsePacket(49): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
20:48:01 Server|CRITICAL > #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
20:48:01 Server|CRITICAL > #6 src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket)
20:48:01 Server|CRITICAL > #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
20:48:01 Server|CRITICAL > #8 src/pocketmine/Player(3513): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
20:48:01 Server|CRITICAL > #9 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
20:48:01 Server|CRITICAL > #10 vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 47.61.239.208 35691, object raklib\protocol\EncapsulatedPacket, integer 0)
20:48:01 Server|CRITICAL > #11 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
20:48:01 Server|CRITICAL > #12 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
20:48:01 Server|CRITICAL > #13 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
20:48:01 Server|CRITICAL > #14 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
20:48:01 Server|CRITICAL > #15 src/pocketmine/Server(2267): pocketmine\snooze\SleeperHandler->sleepUntil(double 1615322881.5507)
20:48:01 Server|CRITICAL > #16 src/pocketmine/Server(2107): pocketmine\Server->tickProcessor()
20:48:01 Server|CRITICAL > #17 src/pocketmine/Server(1691): pocketmine\Server->start()
20:48:01 Server|CRITICAL > #18 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
20:48:01 Server|CRITICAL > #19 src/pocketmine/PocketMine(304): pocketmine\server()
20:48:01 Server|CRITICAL > #20 (11): require(string[63] phar:///home/container/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by AytgDmr1** [comment]
The plugin is outdated probably. I don't have any plans to update.
